Add anaconda channel
The anaconda channel contains asn1crypto / py27 under linux64. Installation fails otherwise (on debian stretch) with message:
NoPackagesFoundError: Package missing in current linux-64 channels: 
  - asn1crypto 0.24.0 py27_0